# Generated by Django 4.2 on 2025-06-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_dashboard_preferences"),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='additional_data',
            new_name='details',
        ),
    ]
