# Generated by Django 4.2 on 2025-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fix_field_renames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardpreference",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="core_activi_action_b2beff_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="core_activi_content_1a7154_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activity_lo_timesta_ef2c57_idx",
            old_name="core_activi_timesta_44c73d_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activity_lo_user_id_072db3_idx",
            old_name="core_activi_user_id_ae0b38_idx",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="description",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="object_id",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("sync", "Synchronization"),
                    ("email", "Email"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="entity_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="entity_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action_type"], name="activity_lo_action__9e4610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="activity_lo_entity__5a4970_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="activitylog",
            table="activity_logs",
        ),
        migrations.DeleteModel(
            name="DashboardPreference",
        ),
    ]
