services:
  - type: web
    name: mobilize-crm
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py fix_users_table
      python manage.py migrate --run-syncdb
      python manage.py createcachetable
      gunicorn mobilize.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mobilize.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 4