# Generated by Django 4.2 on 2025-06-10 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "admin_panel",
            "0003_rename_offices_name_a92a3f_idx_admin_panel_name_832449_idx_and_more",
        ),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("direction", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "gmail_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gmail_thread_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attachments",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sender", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                (
                    "google_calendar_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_meet_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        db_column="church_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_communications",
                        to="churches.church",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        db_column="office_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="admin_panel.office",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_column="person_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_communications",
                        to="contacts.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "db_table": "communications",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_html", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_html", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="email_attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_attachments",
                        to="communications.communication",
                    ),
                ),
            ],
            options={
                "db_table": "django_email_attachments",
            },
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(fields=["name"], name="communicati_name_644026_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["category"], name="communicati_categor_ffffbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsignature",
            index=models.Index(
                fields=["user", "is_default"], name="communicati_user_id_19fdb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["date"], name="comm_date_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["type"], name="comm_type_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["user_id"], name="comm_user_id_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["email_status"], name="comm_email_status_idx"),
        ),
    ]
