# Generated by Django 4.2 on 2025-06-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("direction", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "gmail_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gmail_thread_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attachments",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sender", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                (
                    "google_calendar_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_meet_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "db_table": "communications",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_html", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_html", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_signatures",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="email_attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_attachments",
                        to="communications.communication",
                    ),
                ),
            ],
            options={
                "db_table": "django_email_attachments",
            },
        ),
    ]
