# Generated by Django 4.2 on 2025-06-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("contacts", "0001_initial"),
        ("churches", "0001_initial"),
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="church",
            field=models.ForeignKey(
                blank=True,
                db_column="church_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="church_communications",
                to="churches.church",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="office",
            field=models.ForeignKey(
                blank=True,
                db_column="office_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to="admin_panel.office",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_column="person_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_communications",
                to="contacts.person",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(fields=["name"], name="email_templ_name_4bbac9_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["category"], name="email_templ_categor_e84d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsignature",
            index=models.Index(
                fields=["user", "is_default"], name="email_signa_user_id_1b8b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["date"], name="comm_date_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["type"], name="comm_type_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["user_id"], name="comm_user_id_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["email_status"], name="comm_email_status_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["user_id", "date"], name="communicati_user_id_3d9b0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["type", "date"], name="communicati_type_0cbc3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["office", "date"], name="communicati_office__66e37a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["gmail_message_id"], name="communicati_gmail_m_8945a1_idx"
            ),
        ),
    ]
