# Generated by Django 4.2 on 2025-06-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailsignature",
            new_name="email_signa_user_id_1b8b05_idx",
            old_name="communicati_user_id_19fdb4_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="email_templ_name_4bbac9_idx",
            old_name="communicati_name_644026_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="email_templ_categor_e84d9c_idx",
            old_name="communicati_categor_ffffbf_idx",
        ),
        migrations.AlterModelTable(
            name="emailsignature",
            table="email_signatures",
        ),
        migrations.AlterModelTable(
            name="emailtemplate",
            table="email_templates",
        ),
    ]
