# Generated by Django 4.2 on 2025-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsignature",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="URL to logo image for signature",
                max_length=255,
                null=True,
            ),
        ),
    ]
