# Generated by Django 4.2 on 2025-06-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_add_logo_url_to_email_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsignature",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload logo image file (PNG, JPG)",
                null=True,
                upload_to="signature_logos/",
            ),
        ),
    ]
