# Generated by Django 4.2 on 2025-06-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0004_emailsignature_logo_file"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="communication",
            name="comm_user_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="communication",
            name="communicati_user_id_3d9b0a_idx",
        ),
        migrations.RenameField(
            model_name="communication",
            old_name="user_id",
            new_name="firebase_user_id",
        ),
        migrations.AddField(
            model_name="communication",
            name="archived",
            field=models.BooleanField(
                default=False, help_text="Whether this communication is archived"
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="bcc_recipients",
            field=models.TextField(
                blank=True,
                help_text="BCC recipients as comma-separated emails",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="cc_recipients",
            field=models.TextField(
                blank=True,
                help_text="CC recipients as comma-separated emails",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="content",
            field=models.TextField(
                blank=True, help_text="Email body content", null=True
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if sending failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External message ID (e.g., Gmail message ID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="is_notification",
            field=models.BooleanField(
                default=False, help_text="Whether this is a system notification"
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to="communications.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["firebase_user_id"], name="comm_user_id_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["firebase_user_id", "date"],
                name="communicati_firebas_0e912a_idx",
            ),
        ),
    ]
