# Generated by Django 4.2 on 2025-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_remove_communication_comm_user_id_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="communication",
            name="comm_user_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="communication",
            name="communicati_firebas_0e912a_idx",
        ),
        migrations.RemoveField(
            model_name="communication",
            name="firebase_user_id",
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["user"], name="comm_user_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["user", "date"], name="communicati_user_id_3d9b0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["status"], name="communicati_status_3c4fa3_idx"),
        ),
    ]
