# Generated by Django 4.2 on 2025-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_remove_firebase_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone Call", "Phone Call"),
                    ("Text Message", "Text Message"),
                    ("Meeting", "Meeting"),
                    ("Video Call", "Video Call"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
