# Generated by Django 4.2 on 2025-06-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0008_fix_user_id_column_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="message",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
