# Generated by Django 4.2 on 2025-06-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_add_person_mission_fields"),
        ("communications", "0009_alter_communication_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_communications",
                to="contacts.person",
            ),
        ),
    ]
