# Generated by Django 4.2 on 2025-07-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0010_alter_communication_person"),
    ]

    operations = [
        # Convert created_at from DateField to DateTimeField
        migrations.RunSQL(
            sql="""
            ALTER TABLE communications 
            ALTER COLUMN created_at TYPE timestamp with time zone 
            USING created_at::timestamp with time zone;
            """,
            reverse_sql="""
            ALTER TABLE communications 
            ALTER COLUMN created_at TYPE date 
            USING created_at::date;
            """,
        ),
        # Convert updated_at from DateField to DateTimeField  
        migrations.RunSQL(
            sql="""
            ALTER TABLE communications 
            ALTER COLUMN updated_at TYPE timestamp with time zone 
            USING updated_at::timestamp with time zone;
            """,
            reverse_sql="""
            ALTER TABLE communications 
            ALTER COLUMN updated_at TYPE date 
            USING updated_at::date;
            """,
        ),
    ]
