# Generated by Django 4.2 on 2025-07-17 14:05

from django.db import migrations, connection


def fix_email_templates_schema(apps, schema_editor):
    """Fix email_templates table schema to match Django expectations."""
    with connection.cursor() as cursor:
        # Check if created_by column exists and created_by_id doesn't
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='email_templates' AND table_schema='public'
            AND column_name IN ('created_by', 'created_by_id');
        """
        )
        columns = [row[0] for row in cursor.fetchall()]

        if "created_by" in columns and "created_by_id" not in columns:
            # Rename created_by to created_by_id
            cursor.execute(
                """
                ALTER TABLE email_templates
                RENAME COLUMN created_by TO created_by_id;
            """
            )
            print("Renamed created_by to created_by_id in email_templates table")
        elif "created_by_id" in columns:
            print("email_templates table already has created_by_id column")
        else:
            print(
                "Warning: Neither created_by nor created_by_id found in "
                "email_templates table"
            )


def reverse_fix_email_templates_schema(apps, schema_editor):
    """Reverse the schema fix."""
    with connection.cursor() as cursor:
        # Rename created_by_id back to created_by
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='email_templates' AND table_schema='public'
            AND column_name = 'created_by_id';
        """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE email_templates
                RENAME COLUMN created_by_id TO created_by;
            """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0012_create_gmail_sync_settings"),
    ]

    operations = [
        migrations.RunPython(
            fix_email_templates_schema,
            reverse_fix_email_templates_schema,
        ),
    ]
