# Generated by Django 4.2 on 2025-07-17 14:06

from django.db import migrations, connection


def fix_email_templates_columns(apps, schema_editor):
    """Fix additional column mismatches in email_templates table."""
    with connection.cursor() as cursor:
        # Check current columns
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='email_templates' AND table_schema='public';
        """
        )
        columns = [row[0] for row in cursor.fetchall()]

        # Rename content to body if needed
        if "content" in columns and "body" not in columns:
            cursor.execute(
                """
                ALTER TABLE email_templates
                RENAME COLUMN content TO body;
            """
            )
            print("Renamed content to body in email_templates table")

        # Remove unused columns that might cause issues
        if "variables" in columns:
            cursor.execute(
                """
                ALTER TABLE email_templates
                DROP COLUMN IF EXISTS variables;
            """
            )
            print("Dropped variables column from email_templates table")

        if "office_id" in columns:
            cursor.execute(
                """
                ALTER TABLE email_templates
                DROP COLUMN IF EXISTS office_id;
            """
            )
            print("Dropped office_id column from email_templates table")


def reverse_fix_email_templates_columns(apps, schema_editor):
    """Reverse the column fixes."""
    with connection.cursor() as cursor:
        # Rename body back to content
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='email_templates' AND table_schema='public'
            AND column_name = 'body';
        """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE email_templates
                RENAME COLUMN body TO content;
            """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0013_auto_20250717_1405"),
    ]

    operations = [
        migrations.RunPython(
            fix_email_templates_columns,
            reverse_fix_email_templates_columns,
        ),
    ]
