# Generated by Django 4.2 on 2025-07-17 14:07

from django.db import migrations, connection


def add_is_html_column(apps, schema_editor):
    """Add missing is_html column to email_templates table."""
    with connection.cursor() as cursor:
        # Check if is_html column exists
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='email_templates' AND table_schema='public'
            AND column_name = 'is_html';
        """
        )

        if not cursor.fetchone():
            # Add is_html column with default True
            cursor.execute(
                """
                ALTER TABLE email_templates
                ADD COLUMN is_html BOOLEAN DEFAULT true NOT NULL;
            """
            )
            print("Added is_html column to email_templates table")
        else:
            print("is_html column already exists in email_templates table")


def reverse_add_is_html_column(apps, schema_editor):
    """Remove the is_html column."""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE email_templates
            DROP COLUMN IF EXISTS is_html;
        """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0014_auto_20250717_1406"),
    ]

    operations = [
        migrations.RunPython(
            add_is_html_column,
            reverse_add_is_html_column,
        ),
    ]
