# Generated by Django 4.2 on 2025-06-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_add_performance_indexes"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="person",
            field=models.OneToOneField(
                blank=True,
                help_text="The Person record for this user in the CRM system",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="contacts.person",
            ),
        ),
    ]
