# Generated by Django 4.2 on 2025-06-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_firebase_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_preference', models.CharField(
                    choices=[
                        ('disabled', 'Disabled - No contact sync'),
                        ('crm_only', 'CRM Only - Sync only contacts that exist in CRM'),
                        ('all_contacts', 'All Contacts - Import all Google contacts to CRM')
                    ],
                    default='crm_only',
                    help_text='Choose how Google contacts should be synchronized',
                    max_length=20
                )),
                ('auto_sync_enabled', models.BooleanField(
                    default=True,
                    help_text='Enable automatic contact synchronization'
                )),
                ('sync_frequency_hours', models.PositiveIntegerField(
                    default=24,
                    help_text='How often to sync contacts (in hours)'
                )),
                ('last_sync_at', models.DateTimeField(
                    blank=True,
                    help_text='When contacts were last synced',
                    null=True
                )),
                ('sync_errors', models.JSONField(
                    blank=True,
                    help_text='Any errors from the last sync attempt',
                    null=True
                )),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contact_sync_settings',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Contact Sync Settings',
                'verbose_name_plural': 'Contact Sync Settings',
                'db_table': 'user_contact_sync_settings',
            },
        ),
    ]
