# Generated by Django 4.2 on 2025-06-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useroffice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(fields=["name"], name="admin_panel_name_832449_idx"),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(fields=["code"], name="admin_panel_code_474d6a_idx"),
        ),
        migrations.AddIndex(
            model_name="useroffice",
            index=models.Index(fields=["user"], name="user_office_user_id_c35c9c_idx"),
        ),
        migrations.AddIndex(
            model_name="useroffice",
            index=models.Index(
                fields=["office"], name="user_office_office__18a8f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useroffice",
            index=models.Index(fields=["role"], name="user_office_role_ea37fd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="useroffice",
            unique_together={("user", "office")},
        ),
    ]
