# Generated by Django 4.2 on 2025-06-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="useroffice",
            name="user_office_role_ea37fd_idx",
        ),
        migrations.RemoveField(
            model_name="useroffice",
            name="role",
        ),
    ]
