# Generated by Django 4.2 on 2025-06-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="office",
            new_name="admin_panel_name_832449_idx",
            old_name="offices_name_a92a3f_idx",
        ),
        migrations.RenameIndex(
            model_name="office",
            new_name="admin_panel_code_474d6a_idx",
            old_name="offices_code_856b73_idx",
        ),
        migrations.AlterModelTable(
            name="office",
            table=None,
        ),
    ]
