# Generated by Django 4.2 on 2025-06-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                ("id", models.AutoField(primary_key=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_details",
                        to="contacts.contact",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("denomination", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("congregation_size", models.IntegerField(blank=True, null=True)),
                ("weekly_attendance", models.IntegerField(blank=True, null=True)),
                ("service_times", models.JSONField(blank=True, null=True)),
                ("facilities", models.JSONField(blank=True, null=True)),
                ("ministries", models.JSONField(blank=True, null=True)),
                ("primary_language", models.CharField(blank=True, max_length=50, null=True)),
                ("secondary_languages", models.JSONField(blank=True, null=True)),
                ("pastor_name", models.CharField(blank=True, max_length=200, null=True)),
                ("senior_pastor_first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("senior_pastor_last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("pastor_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("pastor_email", models.EmailField(blank=True, max_length=255, null=True)),
                ("missions_pastor_first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("missions_pastor_last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mission_pastor_phone", models.CharField(blank=True, max_length=255, null=True)),
                ("mission_pastor_email", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact_first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact_last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact_phone", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact_email", models.CharField(blank=True, max_length=255, null=True)),
                ("main_contact_id", models.IntegerField(blank=True, null=True)),
                ("church_pipeline", models.CharField(blank=True, max_length=255, null=True)),
                ("priority", models.CharField(blank=True, max_length=255, null=True)),
                ("assigned_to", models.CharField(blank=True, max_length=255, null=True)),
                ("virtuous", models.BooleanField(blank=True, null=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("referred_by", models.CharField(blank=True, max_length=255, null=True)),
                ("info_given", models.TextField(blank=True, null=True)),
                ("reason_closed", models.TextField(blank=True, null=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("office_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Church",
                "verbose_name_plural": "Churches",
                "db_table": "churches",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="churches_name_idx"),
                ],
            },
        ),
    ]