# Generated by Django 4.2 on 2025-06-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="church_details",
                        serialize=False,
                        to="contacts.contact",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The official name of the church.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "denomination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("congregation_size", models.IntegerField(blank=True, null=True)),
                ("weekly_attendance", models.IntegerField(blank=True, null=True)),
                (
                    "service_times",
                    models.JSONField(
                        blank=True,
                        help_text="e.g., Sunday 9am, Wednesday 7pm",
                        null=True,
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True,
                        help_text="Details about church facilities.",
                        null=True,
                    ),
                ),
                (
                    "ministries",
                    models.JSONField(
                        blank=True,
                        help_text="List or details of church ministries.",
                        null=True,
                    ),
                ),
                (
                    "primary_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "secondary_languages",
                    models.JSONField(
                        blank=True,
                        help_text="Other languages used in services/ministries.",
                        null=True,
                    ),
                ),
                (
                    "pastor_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the senior pastor (replaces senior_pastor_name).",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "senior_pastor_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "senior_pastor_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pastor_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the senior pastor (replaces senior_pastor_phone).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pastor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the senior pastor (replaces senior_pastor_email).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "missions_pastor_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "missions_pastor_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mission_pastor_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mission_pastor_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("main_contact_id", models.IntegerField(blank=True, null=True)),
                (
                    "church_pipeline",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("virtuous", models.BooleanField(blank=True, null=True)),
                ("info_given", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Church",
                "verbose_name_plural": "Churches",
                "db_table": "churches",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(fields=["name"], name="churches_name_f8a649_idx"),
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(
                fields=["church_pipeline"], name="churches_church__67d79e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(
                fields=["denomination"], name="churches_denomin_b59f00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(
                fields=["congregation_size"], name="churches_congreg_94ad91_idx"
            ),
        ),
    ]
