# Generated by Django 4.2 on 2025-06-23 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_add_performance_indexes"),
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("senior_pastor", "Senior Pastor"),
                            ("associate_pastor", "Associate Pastor"),
                            ("youth_pastor", "Youth Pastor"),
                            ("worship_pastor", "Worship Pastor"),
                            ("missions_pastor", "Missions Pastor"),
                            ("admin_pastor", "Administrative Pastor"),
                            ("elder", "Elder"),
                            ("deacon", "Deacon"),
                            ("board_member", "Board Member"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("member", "Member"),
                            ("regular_attendee", "Regular Attendee"),
                            ("volunteer", "Volunteer"),
                            ("committee_member", "Committee Member"),
                            ("ministry_leader", "Ministry Leader"),
                            ("other", "Other"),
                        ],
                        default="member",
                        help_text="The person's role in this church",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Is this person the primary contact for the church?",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When this relationship started",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this relationship ended (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("former", "Former"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this membership/relationship",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="churches.church",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_memberships",
                        to="contacts.person",
                    ),
                ),
            ],
            options={
                "db_table": "church_memberships",
                "ordering": [
                    "-is_primary_contact",
                    "role",
                    "person__contact__last_name",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="churchmembership",
            index=models.Index(
                fields=["church"], name="church_memb_church__065864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="churchmembership",
            index=models.Index(
                fields=["person"], name="church_memb_person__b2c3a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="churchmembership",
            index=models.Index(
                fields=["is_primary_contact"], name="church_memb_is_prim_fb3d7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="churchmembership",
            index=models.Index(fields=["status"], name="church_memb_status_ef9d79_idx"),
        ),
        migrations.AddIndex(
            model_name="churchmembership",
            index=models.Index(fields=["role"], name="church_memb_role_0c1131_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="churchmembership",
            unique_together={("person", "church")},
        ),
    ]
