# Generated by Django 4.2 on 2025-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="church",
            new_name="churches_name_f8a649_idx",
            old_name="churches_name_idx",
        ),
        migrations.AlterField(
            model_name="church",
            name="facilities",
            field=models.JSONField(
                blank=True, help_text="Details about church facilities.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="church",
            name="ministries",
            field=models.JSONField(
                blank=True, help_text="List or details of church ministries.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The official name of the church.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="pastor_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the senior pastor (replaces senior_pastor_email).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="pastor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the senior pastor (replaces senior_pastor_name).",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="pastor_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the senior pastor (replaces senior_pastor_phone).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="secondary_languages",
            field=models.JSONField(
                blank=True,
                help_text="Other languages used in services/ministries.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="service_times",
            field=models.JSONField(
                blank=True, help_text="e.g., Sunday 9am, Wednesday 7pm", null=True
            ),
        ),
    ]
