# Generated by Django 4.2 on 2025-06-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "church_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("initial_notes", models.TextField(blank=True, null=True)),
                (
                    "google_resource_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_contact_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
                ("date_created", models.DateField(blank=True, null=True)),
                ("date_modified", models.DateField(blank=True, null=True)),
                ("last_synced_at", models.DateField(blank=True, null=True)),
                ("office_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("has_conflict", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contacts.contact",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("anniversary", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "home_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("languages", models.TextField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("employer", models.CharField(blank=True, max_length=255, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("interests", models.TextField(blank=True, null=True)),
                ("church_id", models.IntegerField(blank=True, null=True)),
                (
                    "church_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary_contact", models.BooleanField(blank=True, null=True)),
                (
                    "pipeline_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "people_pipeline",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("last_contact", models.DateField(blank=True, null=True)),
                ("next_contact", models.DateField(blank=True, null=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("info_given", models.TextField(blank=True, null=True)),
                ("desired_service", models.TextField(blank=True, null=True)),
                ("reason_closed", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "referred_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=255, null=True)),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("virtuous", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "people",
                "ordering": ["last_name", "first_name"],
            },
            bases=("contacts.contact",),
        ),
    ]
