# Generated by Django 4.2 on 2025-06-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("person", "Person"), ("church", "Church")],
                        help_text="Type of contact: Person or Church",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "church_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email address, unique if provided.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="General notes about the contact.",
                        null=True,
                    ),
                ),
                ("initial_notes", models.TextField(blank=True, null=True)),
                (
                    "google_resource_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_contact_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateField(blank=True, null=True)),
                ("date_modified", models.DateField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("has_conflict", models.BooleanField(blank=True, null=True)),
                (
                    "pipeline_stage",
                    models.CharField(
                        blank=True,
                        help_text="Current stage in the engagement pipeline.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="Priority level (e.g., low, medium, high).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="Status of the contact (e.g., active, inactive).",
                        max_length=20,
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of last interaction.", null=True
                    ),
                ),
                (
                    "next_contact_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date for next interaction.",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, help_text="JSON field for storing tags.", null=True
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, help_text="JSON field for custom data.", null=True
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        db_column="office_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_by_office",
                        to="admin_panel.office",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="person_details",
                        serialize=False,
                        to="contacts.contact",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("anniversary", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "spouse_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "home_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("languages", models.JSONField(blank=True, null=True)),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "church_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("twitter_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_contact_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "people",
                "ordering": ["contact__last_name", "contact__first_name"],
            },
        ),
    ]
