# Generated by Django 4.2 on 2025-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="people_user_id",
            field=models.CharField(
                blank=True, db_column="user_id", max_length=255, null=True
            ),
        ),
    ]
