# Generated by Django 4.2 on 2025-06-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="primary_church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="churches.church",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["type"], name="contacts_type_124b94_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["pipeline_stage"], name="contacts_pipelin_b078f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["office"], name="contacts_office__8e5258_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="contacts_email_2eb381_idx"),
        ),
    ]
