# Generated by Django 4.2 on 2025-06-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_pipeline_stage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_pipelin_b078f8_idx",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="pipeline_stage",
        ),
    ]
