# Generated by Django 4.2 on 2025-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_remove_contact_contacts_pipelin_b078f8_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                help_text="Priority level (e.g., low, medium, high).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Status of the contact (e.g., active, inactive).",
                max_length=20,
            ),
        ),
    ]
