# Generated by Django 4.2 on 2025-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contact_priority_alter_contact_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["first_name"], name="contacts_first_n_ad09a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["last_name"], name="contacts_last_na_c4a194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["priority"], name="contacts_priorit_ac275b_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["status"], name="contacts_status_f623d1_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["created_at"], name="contacts_created_4c6582_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["type", "priority"], name="contacts_type_2812d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["type", "office"], name="contacts_type_dd7ee4_idx"
            ),
        ),
    ]
