# Generated by Django 4.2 on 2025-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-- Select Status --"),
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("engaged", "Engaged"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
