# Generated by Django 4.2 on 2025-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_add_marital_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="desired_service",
            field=models.TextField(
                blank=True, help_text="Desired service location or type", null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="info_given",
            field=models.TextField(
                blank=True,
                help_text="Information about mission/vision shared",
                null=True,
            ),
        ),
    ]
