# Generated by Django 4.2 on 2025-06-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        # Add contact field
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contact_tasks',
                to='contacts.contact',
                db_column='contact_id'
            ),
        ),
        # Add recurring task fields
        migrations.AddField(
            model_name='task',
            name='recurring_pattern',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='Defines the recurrence rule, e.g., weekly, monthly.'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring_template',
            field=models.BooleanField(
                default=False,
                help_text='Is this the master template for a recurring task series?'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_end_date',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Date when the recurring series should end.'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='occurrences',
                to='tasks.task',
                help_text='Link to the master recurring task if this is an occurrence.'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='For template tasks, when the next occurrence should be generated.'
            ),
        ),
        # Add index for recurring tasks
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['is_recurring_template', 'next_occurrence_date'],
                name='tasks_recurring_idx'
            ),
        ),
    ]
