# Generated by Django 4.2 on 2025-06-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_add_marital_status_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0003_remove_useroffice_role"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notification_sent",
            field=models.BooleanField(
                default=False, help_text="Whether due date notification has been sent"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="overdue_notification_sent",
            field=models.BooleanField(
                default=False, help_text="Whether overdue notification has been sent"
            ),
        ),
        migrations.CreateModel(
            name="RecurringTaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=50,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(default="general", max_length=50)),
                (
                    "recurrence_pattern",
                    models.JSONField(help_text="Recurrence pattern configuration"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_created",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last task was created from this template",
                        null=True,
                    ),
                ),
                (
                    "send_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send assignment notifications for created tasks",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_recurring_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_task_templates",
                        to="contacts.contact",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_task_templates",
                        to="admin_panel.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Task Template",
                "verbose_name_plural": "Recurring Task Templates",
                "db_table": "recurring_task_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="recurring_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the recurring template that created this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_tasks",
                to="tasks.recurringtasktemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtasktemplate",
            index=models.Index(
                fields=["is_active"], name="recurring_t_is_acti_88a674_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtasktemplate",
            index=models.Index(
                fields=["last_created"], name="recurring_t_last_cr_4a3229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtasktemplate",
            index=models.Index(
                fields=["created_by"], name="recurring_t_created_33be00_idx"
            ),
        ),
    ]
