# Generated by Django 4.2 on 2025-06-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_add_missing_task_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_is_recu_6e9728_idx",
            old_name="tasks_recurring_idx",
        ),
    ]
