# Generated by Django 4.2 on 2025-06-10 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("churches", "0001_initial"),
        ("contacts", "0001_initial"),
        (
            "admin_panel",
            "0003_rename_offices_name_a92a3f_idx_admin_panel_name_832449_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("people", "People Pipeline"),
                            ("church", "Church Pipeline"),
                            ("custom", "Custom Pipeline"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_main_pipeline", models.BooleanField(default=False, null=True)),
                (
                    "parent_pipeline_stage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipelines",
                        to="admin_panel.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline",
                "verbose_name_plural": "Pipelines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PipelineContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("person", "Person"), ("church", "Church")],
                        default="person",
                        max_length=10,
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_entries",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Contact",
                "verbose_name_plural": "Pipeline Contacts",
            },
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_move_days", models.IntegerField(blank=True, null=True)),
                ("auto_reminder", models.BooleanField(default=False, null=True)),
                ("auto_task_template", models.TextField(blank=True, null=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="pipeline.pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Stage",
                "verbose_name_plural": "Pipeline Stages",
                "ordering": ["pipeline", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_stage_history",
                        to="pipeline.pipelinestage",
                    ),
                ),
                (
                    "pipeline_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="pipeline.pipelinecontact",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_stage_history",
                        to="pipeline.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Stage History",
                "verbose_name_plural": "Pipeline Stage History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pipelinecontact",
            name="current_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_contacts",
                to="pipeline.pipelinestage",
            ),
        ),
        migrations.AddField(
            model_name="pipelinecontact",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_entries",
                to="contacts.person",
            ),
        ),
        migrations.AddField(
            model_name="pipelinecontact",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="pipeline.pipeline",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagehistory",
            index=models.Index(
                fields=["pipeline_contact"], name="pipeline_pi_pipelin_8edd6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagehistory",
            index=models.Index(
                fields=["from_stage"], name="pipeline_pi_from_st_be317e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagehistory",
            index=models.Index(
                fields=["to_stage"], name="pipeline_pi_to_stag_e3f3da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagehistory",
            index=models.Index(
                fields=["created_at"], name="pipeline_pi_created_19a3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestage",
            index=models.Index(fields=["name"], name="pipeline_pi_name_85ec52_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinestage",
            index=models.Index(
                fields=["pipeline", "order"], name="pipeline_pi_pipelin_eeedc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["person"], name="pipeline_pi_person__3251a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["church"], name="pipeline_pi_church__3d8a01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["contact_type"], name="pipeline_pi_contact_a5ef2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["pipeline"], name="pipeline_pi_pipelin_1fd84c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["current_stage"], name="pipeline_pi_current_03662b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["entered_at"], name="pipeline_pi_entered_ae53f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["name"], name="pipeline_pi_name_5d7b23_idx"),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["pipeline_type"], name="pipeline_pi_pipelin_72235d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["office"], name="pipeline_pi_office__278687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["is_main_pipeline"], name="pipeline_pi_is_main_88c7cf_idx"
            ),
        ),
    ]
