# Generated by Django 4.2 on 2025-06-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="is_main_pipeline",
            field=models.BooleanField(
                default=False,
                help_text="True for the global Main People/Church pipelines",
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="office",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL for main pipelines (shared), set for custom pipelines (office-specific)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipelines",
                to="admin_panel.office",
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="parent_pipeline_stage",
            field=models.CharField(
                blank=True,
                help_text="For custom pipelines: the main pipeline stage this custom pipeline falls under (e.g. 'promotion', 'information')",
                max_length=100,
                null=True,
            ),
        ),
    ]
