# Generated by Django 4.2 on 2025-06-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_remove_contact_contacts_pipelin_b078f8_idx_and_more"),
        ("churches", "0001_initial"),
        ("pipeline", "0002_alter_pipeline_is_main_pipeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinecontact",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct link to Contact model (preferred approach)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_entries",
                to="contacts.contact",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinecontact",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy field - use contact field instead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_pipeline_entries",
                to="churches.church",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinecontact",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy field - use contact field instead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_pipeline_entries",
                to="contacts.person",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecontact",
            index=models.Index(
                fields=["contact"], name="pipeline_pi_contact_235a2a_idx"
            ),
        ),
    ]
